### ISSUE TITLE
question on bob_preload

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-m2pc#5]
The following is the code of `bob_preload` in the class `Malicious`.

```
void bob_preload(){
		int sent = fio->bytes_sent;
		delete fio;
		fio = new FileIO(GC_FILE.c_str(), true);
		mio = new MemIO(0);
		mio->load_from_file(fio, sent);
		delete fio;
}
```

So it actually uses the `fio->bytes_sent` from `bob_offline()` assuming it is run before the `bob_preload()`. I guess it is for experiment purpose because, for measurement, we run offline and then test in online.

If offline and online are highly separated (garble today and use tomorrow), I guess `sent` here should be retrieved from the file size of `GC_FILE.c_str()`? 

considering to submit a short PR for this.

**Comment by wangxiao1254** [comment]
You are right.

**Comment by weikengchen** [comment]
:( now trying to debug a possible compatibility problem that in my Mac. The test `sha256` fails every time because `res4=1` means `cheat=true`. will post something back when there is a result. 

(It is still unresolved... now adding `emp-readme` with Mac support to have Travis help me)

Enjoy CCS'17!

**Comment by wangxiao1254** [comment]
Seems that after your fix in emp-tool, travis tests pass just fine.

It is no urgent to make it decoupled :)

**Comment by weikengchen** [comment]
the current difficulty is that: in my Mac, `emp-m2pc` test `sha256` failed because `WRONG ANS!`. The reason is `res4=1` and `cheat=true`. 

It is super strange :(       I am trying to debug

not sure whether it is only for me or for everyone. so decide to enable Travis to test in Mac first.

**Comment by weikengchen** [comment]
Adding `emp-toolkit` with Mac support has encountered a very specific problem with Travis --

Travis's `osx` does not support AES-NI :(

**Comment by wangxiao1254** [comment]
I once tried to add osx in travis and met the same problem during the summer. Maybe it is a good idea to migrate to circuit CI and stop using travis.

**Comment by weikengchen** [comment]
nope. Circuit CI is not free for OSX (I used the free 2-week trial). But they have an application-based way to apply for a free account for open-source projects, by sending emails for a request.

https://circleci.com/pricing/#faq-section-os-x

This is a diplomatic work :(

**Comment by weikengchen** [comment]
Wait! We both make a mistake. It is **Circle** CI :)

(but I would like to especially thank Circuit ORAM and its authors)
