### ISSUE TITLE
My Mac fails because `NETWORK_BUFFER_SIZE` not sufficient for `sha256` in `emp-m2pc`

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-m2pc#7]
OK:) this is not an easy debug. I found the reason why my Mac always fails for `sha256` in `emp-m2pc` due to `res4=1` and Alice `cheat=1`, showing `WRONG_ANS`.

It seems that my Mac has a terrible loopback network (or I guess too fast?). The standard `NETWORK_BUFFER_SIZE` in `emp_tool/utils/constants.h` will make buffer insufficient and cause data loss -- the result is that Bob 'cheats' and the result for `sha256` in `emp-m2pc` is wrong in my specific case.

My question is:
During the EUROCRYPT'17 paper and previous works on emp-toolkit, will a very high `NETWORK_BUFFER_SIZE` obviously hurts the performance (due to the loss of locality?)? If this performance change is not obvious, maybe the default value for `NETWORK_BUFFER_SIZE` in `emp-tool/utils/constants.h` can be changed to a larger one.

(I see the comment nearby said that this value should be adjusted for the specific network. I feel that this value should increase for `emp-m2pc` because the evaluation is slower, the network can be too fast.)

**Comment by weikengchen** [comment]
And Thanks to Xiao Wang!

**Comment by weikengchen** [comment]
An alternative way is to give a boosting for `emp-m2pc` on `NETWORK_BUFFER_SIZE`?

Note that the value of `NETWORK_BUFFER_SIZE` would be hardcoded into the binary of `emp-tool`.

**Comment by wangxiao1254** [comment]
I believe that buffer size only affects performance but not correctness. I
will explain more when I have time later.

**Comment by weikengchen** [comment]
will double check

**Comment by weikengchen** [comment]
The real reason found. will send a PR.

**Comment by weikengchen** [comment]
https://github.com/emp-toolkit/emp-tool/pull/34

**Comment by weikengchen** [comment]
It turns out that my Mac adopts `boost`. I will submit another PR to let Mac use socket.
