### ISSUE TITLE
Stack Smashing Error with Examples

### ISSUE THREAD

**Issue by mayank0403** [emp-toolkit/emp-m2pc#8]
After compiling the project, when I try to run the examples, I get `"*** stack smashing detected ***: ./bin/sha1 terminated"`. This happens with all the examples included in the `test` directory.

I am running `./run ./bin/sha1 12345`. The same happens with `./bin/sha1 1 12345` and `./bin/sha1 2 12345`.

But, I am able to run the examples of `emp-sh2pc` correctly.

**Comment by wangxiao1254** [comment]
Should be fixed by now.
